import Link from "next/link";
import { ArrowLeft, AlertCircle, TrendingDown, Info, ShieldAlert } from "lucide-react";

export const metadata = {
  title: "Financial Disclaimer | SpendWise",
  description: "SpendWise Financial & Investment Disclaimer"
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#08070b] text-zinc-300">
      {/* Header */}
      <header className="sticky top-0 z-30 border-b border-zinc-800/80 bg-[#08070b]/90 backdrop-blur">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2 text-sm font-semibold text-zinc-400 hover:text-white transition-colors">
            <ArrowLeft size={16} /> Back to SpendWise
          </Link>
          <div className="text-xl font-black tracking-tight">
            SPEND<span className="text-violet-400">WISE</span>
          </div>
        </div>
      </header>

      {/* Hero */}
      <div className="relative border-b border-zinc-800/60 bg-gradient-to-b from-amber-500/10 via-zinc-950/50 to-transparent py-14 px-6">
        <div className="mx-auto max-w-4xl text-center">
          <div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-amber-500/15 text-amber-300 ring-1 ring-amber-500/30">
            <ShieldAlert size={24} />
          </div>
          <h1 className="text-3xl font-black tracking-tight text-white md:text-5xl">Financial Disclaimer</h1>
          <p className="mt-3 text-sm text-zinc-400">
            Please review our non-advisory disclaimer regarding budgeting, investing, and financial scores.
          </p>
        </div>
      </div>

      {/* Main */}
      <main className="mx-auto max-w-4xl px-6 py-12">
        <div className="space-y-8 rounded-3xl border border-zinc-800/80 bg-zinc-950/60 p-6 md:p-10 backdrop-blur-xl">
          
          <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5 text-amber-200">
            <div className="flex items-center gap-3 mb-2">
              <AlertCircle className="text-amber-400 shrink-0" size={20} />
              <h2 className="font-bold text-base text-amber-300">General Disclaimer</h2>
            </div>
            <p className="text-sm leading-relaxed text-zinc-300">
              SpendWise is a personal expense tracking, budgeting, and financial analytics software tool. SpendWise is not an investment advisor, financial planner, broker-dealer, credit counselor, or tax advisor. None of the content, scores, charts, savings calculations, or badges generated by the Platform should be interpreted as financial advice.
            </p>
          </div>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <span className="text-violet-400">1.</span> Information for Educational &amp; Tracking Purposes Only
            </h2>
            <p className="text-sm leading-relaxed text-zinc-400">
              All tools, forecasts (e.g. 1-Year Savings Forecast), and financial scores (e.g. 50/30/20 health assessment) are mathematical projections based solely on the data you enter. They do not account for taxes, market fluctuations, inflation, individual credit standing, or unforeseen emergencies.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <span className="text-violet-400">2.</span> Investment Decisions &amp; Risks
            </h2>
            <p className="text-sm leading-relaxed text-zinc-400">
              Any reference to investments, SIPs, savings targets, or financial instruments on this site does not constitute a recommendation to buy, sell, or hold any security, mutual fund, cryptocurrency, or asset. Investments in securities markets are subject to market risks; please read all related scheme documents carefully before investing. Consult a licensed SEBI / FINRA certified financial advisor for personalized advice.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">
              <span className="text-violet-400">3.</span> User Responsibility &amp; Accuracy
            </h2>
            <p className="text-sm leading-relaxed text-zinc-400">
              The calculations rendered by SpendWise rely entirely on the accuracy and timeliness of user inputs. We make no representations or warranties regarding the absolute precision or completeness of calculations, category summaries, or EMI schedules.
            </p>
          </section>

        </div>

        {/* Footer Navigation */}
        <div className="mt-12 flex flex-wrap items-center justify-between gap-4 border-t border-zinc-800/80 pt-6 text-xs text-zinc-500">
          <p>© {new Date().getFullYear()} SpendWise. All rights reserved.</p>
          <div className="flex gap-4">
            <Link href="/terms" className="hover:text-violet-400 transition-colors">Terms of Service</Link>
            <Link href="/privacy" className="hover:text-violet-400 transition-colors">Privacy Policy</Link>
            <Link href="/contact" className="hover:text-violet-400 transition-colors">Contact Support</Link>
            <Link href="/about" className="hover:text-violet-400 transition-colors">About</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
